//
// Tier1~4 allowlist data for structure:add-dir per RULESET.md §D, §E (WP4).
// Consumed by structureAddDirConfigSets.ts and structureAddDirConfig.ts.
//

// --- CAF Tier1~4 allowlists (WP1). See shared/context/documentation/CAF_ALLOWLIST_SPEC.md ---

/** Tier1: Allowed words for workload/application/project names (CAF + project). */
export const TIER1_WORKLOAD = new Set([
  'shared',
  'client',
  'application',
  'navigator',
  'emissions',
  'sharepoint',
  'hadoop',
  'config',
  'system',
]);

/** Tier2: Allowed resource type values — major abbreviations (as-is) + full forms for non-major. */
export const TIER2_RESOURCE_TYPE = new Set([
  // Major (keep as-is) — CAF_ALLOWLIST_SPEC § Tier2 Major
  'app',
  'redis',
  'sql',
  'test',
  'prod',
  'dev',
  'qa',
  'stage',
  'config',
  'log',
  // Non-major (full form only in names) — CAF_ALLOWLIST_SPEC § Tier2 Non-major
  'resourcegroup',
  'storage',
  'virtualmachine',
  'virtualnetwork',
  'function',
  'sqldatabase',
  'keyvault',
  'networkinterface',
  'networksecuritygroup',
  'publicip',
  'virtualnetworkgateway',
  'subnet',
  'cosmosdb',
  'datafactory',
  'eventhub',
  'servicebusnamespace',
  'servicebusqueue',
  'servicebustopic',
  'apimanagement',
  'containerregistry',
  'kubernetesservice',
  'mysqldatabase',
  'postgresql',
  'sqlmanagedinstance',
  'datalakestore',
  'synapseworkspace',
  'machinelearningworkspace',
  'openai',
  'applicationinsights',
  'appserviceenvironment',
  'appserviceplan',
  'virtualmachinescaleset',
  'privatelink',
  'privateendpoint',
  'azurefirewall',
  'applicationgateway',
  'recoveryservicesvault',
  'managementgroup',
  'templatespec',
  'automationaccount',
  'logicapp',
  'integrationaccount',
  'botservice',
  'search',
  'maps',
  'signalr',
  'webpubsub',
  // Project Tier2 (non-CAF) per §E
  'context',
  'documentation',
  'scripts',
  'infra',
  'schema',
  'seed',
  'material',
  'ontology',
  'record',
  'reference',
  'content',
  'assessment',
  'bank',
  'diagnose',
  'instruction',
  'recommend',
  'review',
  'governance',
  'identity',
  'achievement',
  'actors',
  'analysis',
  'briefing',
  'curriculum',
  'outlook',
  'schedule',
  'report',
  'analytics',
  'plagiarism',
  'query',
  'teams',
  'sql_kv',
  'db_list_all',
  'git_hooks',
  // Project Tier2 (runtime store base)
  'runtime',
  'store',
]);

/** Tier2: Abbreviation → full form mapping for non-major resource types (normalization). */
export const TIER2_ABBREV_TO_FULL: Readonly<Record<string, string>> = {
  rg: 'resourcegroup',
  st: 'storage',
  vm: 'virtualmachine',
  vnet: 'virtualnetwork',
  func: 'function',
  sqldb: 'sqldatabase',
  kv: 'keyvault',
  nic: 'networkinterface',
  nsg: 'networksecuritygroup',
  pip: 'publicip',
  vgw: 'virtualnetworkgateway',
  snet: 'subnet',
  cosmos: 'cosmosdb',
  adf: 'datafactory',
  evh: 'eventhub',
  sbns: 'servicebusnamespace',
  sbq: 'servicebusqueue',
  sbt: 'servicebustopic',
  apim: 'apimanagement',
  cr: 'containerregistry',
  aks: 'kubernetesservice',
  mysql: 'mysqldatabase',
  psql: 'postgresql',
  sqlmi: 'sqlmanagedinstance',
  dls: 'datalakestore',
  synw: 'synapseworkspace',
  mlw: 'machinelearningworkspace',
  oai: 'openai',
  appi: 'applicationinsights',
  ase: 'appserviceenvironment',
  asp: 'appserviceplan',
  vmss: 'virtualmachinescaleset',
  pl: 'privatelink',
  pep: 'privateendpoint',
  afw: 'azurefirewall',
  agw: 'applicationgateway',
  rsv: 'recoveryservicesvault',
  mg: 'managementgroup',
  ts: 'templatespec',
  aa: 'automationaccount',
  logic: 'logicapp',
  ia: 'integrationaccount',
  bot: 'botservice',
  srch: 'search',
  map: 'maps',
  sigr: 'signalr',
  wps: 'webpubsub',
} as const;

/** Tier3: Environment (CAF) + project subdomain/feature segment values per §E. */
export const TIER3_ENVIRONMENT = new Set([
  // CAF environment
  'prod',
  'dev',
  'test',
  'qa',
  'stage',
  // Project Tier3 (subdomain / feature group)
  'documentation',
  'mapping',
  'schema',
  'seed',
  'material',
  'ontology',
  'reference',
  'assessment',
  'bank',
  'diagnose',
  'instruction',
  'recommend',
  'review',
  'achievement',
  'actors',
  'analysis',
  'briefing',
  'curriculum',
  'outlook',
  'schedule',
  'analytics',
  'plagiarism',
  'query',
  'teams',
  'sql',
  'sql_kv',
  'db_list_all',
  'store',
]);

/** Tier4: Region (CAF) + project Tier4 segment values per §E. */
export const TIER4_REGION = new Set([
  // CAF region example list
  'eastus',
  'eastus2',
  'westus',
  'westus2',
  'westus3',
  'centralus',
  'southcentralus',
  'northcentralus',
  'westeurope',
  'northeurope',
  'uksouth',
  'francecentral',
  'germanywestcentral',
  'canadacentral',
  'brazilsouth',
  'australiaeast',
  'southeastasia',
  'eastasia',
  'japaneast',
  'koreacentral',
  // Project Tier4 (sub-subdomain)
  'material',
  'ontology',
  'sql',
  'db_list_all',
]);
