//
// CAF Component 1–4 allowlist data for Azure resource naming (CAF). See
// MANUAL.md § CAF allowlist specification. Not used for
// directory path validation; directory allowlist is
// config/structure_allowed_dirs.toml only.
// Segment values (e.g. resourcegroup) are CAF name segments; in docs use
// ARM prose terms (e.g. resource group, resource type).
//

/** Component 1: CAF workload/application names only. */
export const COMPONENT1_WORKLOAD = new Set([
  'shared',
  'client',
  'application',
  'navigator',
  'emissions',
  'sharepoint',
  'hadoop',
]);

/** Component 2: CAF resource type — major (as-is) + non-major full form. */
export const COMPONENT2_RESOURCE_TYPE = new Set([
  'app',
  'redis',
  'sql',
  'test',
  'prod',
  'dev',
  'qa',
  'stage',
  'config',
  'log',
  'resourcegroup',
  'storage',
  'virtualmachine',
  'virtualnetwork',
  'function',
  'sqldatabase',
  'keyvault',
  'networkinterface',
  'networksecuritygroup',
  'publicip',
  'virtualnetworkgateway',
  'subnet',
  'cosmosdb',
  'datafactory',
  'eventhub',
  'servicebusnamespace',
  'servicebusqueue',
  'servicebustopic',
  'apimanagement',
  'containerregistry',
  'kubernetesservice',
  'mysqldatabase',
  'postgresql',
  'sqlmanagedinstance',
  'datalakestore',
  'synapseworkspace',
  'machinelearningworkspace',
  'openai',
  'applicationinsights',
  'appserviceenvironment',
  'appserviceplan',
  'virtualmachinescaleset',
  'privatelink',
  'privateendpoint',
  'azurefirewall',
  'applicationgateway',
  'recoveryservicesvault',
  'managementgroup',
  'templatespec',
  'automationaccount',
  'logicapp',
  'integrationaccount',
  'botservice',
  'search',
  'maps',
  'signalr',
  'webpubsub',
]);

/** Component 2: Abbreviation → full form (CAF normalization). */
export const COMPONENT2_ABBREV_TO_FULL: Readonly<Record<string, string>> = {
  rg: 'resourcegroup',
  st: 'storage',
  vm: 'virtualmachine',
  vnet: 'virtualnetwork',
  func: 'function',
  sqldb: 'sqldatabase',
  kv: 'keyvault',
  nic: 'networkinterface',
  nsg: 'networksecuritygroup',
  pip: 'publicip',
  vgw: 'virtualnetworkgateway',
  snet: 'subnet',
  cosmos: 'cosmosdb',
  adf: 'datafactory',
  evh: 'eventhub',
  sbns: 'servicebusnamespace',
  sbq: 'servicebusqueue',
  sbt: 'servicebustopic',
  apim: 'apimanagement',
  cr: 'containerregistry',
  aks: 'kubernetesservice',
  mysql: 'mysqldatabase',
  psql: 'postgresql',
  sqlmi: 'sqlmanagedinstance',
  dls: 'datalakestore',
  synw: 'synapseworkspace',
  mlw: 'machinelearningworkspace',
  oai: 'openai',
  appi: 'applicationinsights',
  ase: 'appserviceenvironment',
  asp: 'appserviceplan',
  vmss: 'virtualmachinescaleset',
  pl: 'privatelink',
  pep: 'privateendpoint',
  afw: 'azurefirewall',
  agw: 'applicationgateway',
  rsv: 'recoveryservicesvault',
  mg: 'managementgroup',
  ts: 'templatespec',
  aa: 'automationaccount',
  logic: 'logicapp',
  ia: 'integrationaccount',
  bot: 'botservice',
  srch: 'search',
  map: 'maps',
  sigr: 'signalr',
  wps: 'webpubsub',
} as const;

/** Component 3: CAF environment only. */
export const COMPONENT3_ENVIRONMENT = new Set([
  'prod',
  'dev',
  'test',
  'qa',
  'stage',
]);

/** Component 4: CAF region example set only. */
export const COMPONENT4_REGION = new Set([
  'eastus',
  'eastus2',
  'westus',
  'westus2',
  'westus3',
  'centralus',
  'southcentralus',
  'northcentralus',
  'westeurope',
  'northeurope',
  'uksouth',
  'francecentral',
  'germanywestcentral',
  'canadacentral',
  'brazilsouth',
  'australiaeast',
  'southeastasia',
  'eastasia',
  'japaneast',
  'koreacentral',
]);
