#!/usr/bin/env sh
# Pre-commit: lint and format check. Enable with:
#   git config core.hooksPath .githooks
#   chmod +x .githooks/pre-commit
set -e
cd "$(git rev-parse --show-toplevel)"
deno lint
deno fmt --check
deno task line-length-check
