//
// CAF Component 1–4 allowlist data for Azure resource naming (CAF). See
// MANUAL.md § CAF allowlist specification. Used for CAF-style resource
// and document naming only, not for directory path validation.
// Segment values (e.g. resource_group) are CAF name segments; in docs use
// ARM prose terms (e.g. resource group, resource type).
//

/** Component 1: CAF workload/application names only. */
export const COMPONENT1_WORKLOAD = new Set([
  'analytics',
  'application',
  'api',
  'auth',
  'backend',
  'billing',
  'client',
  'dashboard',
  'emissions',
  'gateway',
  'hadoop',
  'identity',
  'ingest',
  'navigator',
  'orders',
  'pipeline',
  'portal',
  'reporting',
  'scheduler',
  'sharepoint',
  'shared',
  'sso',
  'storefront',
  'sync',
  'web',
  'warehouse',
  'worker',
]);

/** Component 2: CAF resource type — major (as-is) + non-major full form. */
export const COMPONENT2_RESOURCE_TYPE = new Set([
  'app',
  'redis',
  'sql',
  'test',
  'prod',
  'dev',
  'qa',
  'stage',
  'config',
  'log',
  'resource_group',
  'storage',
  'virtual_machine',
  'virtual_network',
  'function',
  'sql_database',
  'key_vault',
  'network_interface',
  'network_security_group',
  'public_ip',
  'virtual_network_gateway',
  'subnet',
  'cosmos_db',
  'data_factory',
  'event_hub',
  'service_bus_namespace',
  'service_bus_queue',
  'service_bus_topic',
  'api_management',
  'container_registry',
  'kubernetes_service',
  'mysql_database',
  'postgresql',
  'sql_managed_instance',
  'datalake_store',
  'synapse_workspace',
  'machine_learning_workspace',
  'openai',
  'application_insights',
  'app_service_environment',
  'app_service_plan',
  'virtual_machine_scale_set',
  'private_link',
  'private_endpoint',
  'azure_firewall',
  'application_gateway',
  'recovery_services_vault',
  'management_group',
  'template_spec',
  'automation_account',
  'logic_app',
  'integration_account',
  'bot_service',
  'search',
  'maps',
  'signalr',
  'web_pub_sub',
]);

/** Component 2: Abbreviation → full form (CAF normalization). */
export const COMPONENT2_ABBREV_TO_FULL: Readonly<Record<string, string>> = {
  rg: 'resource_group',
  st: 'storage',
  vm: 'virtual_machine',
  vnet: 'virtual_network',
  func: 'function',
  sqldb: 'sql_database',
  kv: 'key_vault',
  nic: 'network_interface',
  nsg: 'network_security_group',
  pip: 'public_ip',
  vgw: 'virtual_network_gateway',
  snet: 'subnet',
  cosmos: 'cosmos_db',
  adf: 'data_factory',
  evh: 'event_hub',
  sbns: 'service_bus_namespace',
  sbq: 'service_bus_queue',
  sbt: 'service_bus_topic',
  apim: 'api_management',
  cr: 'container_registry',
  aks: 'kubernetes_service',
  mysql: 'mysql_database',
  psql: 'postgresql',
  sqlmi: 'sql_managed_instance',
  dls: 'datalake_store',
  synw: 'synapse_workspace',
  mlw: 'machine_learning_workspace',
  oai: 'openai',
  appi: 'application_insights',
  ase: 'app_service_environment',
  asp: 'app_service_plan',
  vmss: 'virtual_machine_scale_set',
  pl: 'private_link',
  pep: 'private_endpoint',
  afw: 'azure_firewall',
  agw: 'application_gateway',
  rsv: 'recovery_services_vault',
  mg: 'management_group',
  ts: 'template_spec',
  aa: 'automation_account',
  logic: 'logic_app',
  ia: 'integration_account',
  bot: 'bot_service',
  srch: 'search',
  map: 'maps',
  sigr: 'signalr',
  wps: 'web_pub_sub',
} as const;

/**
 * Component 3: CAF environment allowlist. Includes environment values (prod, dev,
 * test, qa, stage) and Azure resource type last segments (e.g. from paths like
 * discoveryHubs / applications / members → members). Source: [Tag support for
 * resources](https://docs.azure.cn/en-us/azure-resource-manager/management/tag-support).
 * Reference only for validation; see RULESET.md §E.
 */
export const COMPONENT3_ENVIRONMENT = new Set([
  'prod',
  'dev',
  'test',
  'qa',
  'stage',
  'acknowledge',
  'activate',
  'activated_database',
  'application_registration_invites',
  'applications',
  'archives',
  'arc_settings',
  'artifacts',
  'assess_for_migration',
  'asset_filters',
  'assets',
  'attached_database_configurations',
  'authorization_rules',
  'auto_export_jobs',
  'auto_import_jobs',
  'auto_upgrade_profiles',
  'backup_long_term_retention_policies',
  'backup_short_term_retention_policies',
  'bare_metal_machine_key_sets',
  'bmc_key_sets',
  'builds',
  'calculate_refund',
  'cancel',
  'capacity_reservations',
  'change_directory',
  'cloud_endpoints',
  'components',
  'config_servers',
  'configurations',
  'connection_acls',
  'connections',
  'connection_monitors',
  'consoles',
  'consumer_groups',
  'custom_rollouts',
  'custom_domains',
  'database_connections',
  'data_connections',
  'data_references',
  'databases',
  'data_exports',
  'data_masking_policies',
  'data_sources',
  'deactivate',
  'deactivate_database',
  'default_rollouts',
  'deployments',
  'diagnostic_settings',
  'disk_restore_points',
  'domains',
  'event_channels',
  'event_grid_filters',
  'event_subscriptions',
  'event_hub_connections',
  'event_hubs',
  'executions',
  'experimentation',
  'export_pipelines',
  'extensions',
  'eureka_servers',
  'federated_identity_credentials',
  'flow_logs',
  'gates',
  'generate_sas_token',
  'get_callback_config',
  'get_credentials',
  'geo_backup_policies',
  'groups',
  'hybrid_runbook_worker_groups',
  'hybrid_runbook_workers',
  'hybrid_connections',
  'hybrid_identity_metadata',
  'import_image',
  'import_jobs',
  'import_pipelines',
  'instance_views',
  'job_accounts',
  'job_agents',
  'jobs',
  'key_vault_settings',
  'keys',
  'key_values',
  'ledger_digest_uploads',
  'lenses',
  'linked_backends',
  'linked_storage_accounts',
  'live_outputs',
  'localized_definitions',
  'logs',
  'managed_apis',
  'managed_namespaces',
  'managed_private_endpoints',
  'members',
  'merge',
  'metric_definitions',
  'metrics',
  'metrics_configurations',
  'migration_configurations',
  'migration_entity_groups',
  'migration_entities',
  'migrations',
  'multi_role_pools',
  'network_config',
  'network_interfaces',
  'network_security_perimeter_association_proxies',
  'network_security_perimeter_configurations',
  'network_rule_sets',
  'node_types',
  'offers',
  'origin_groups',
  'origins',
  'ou_container',
  'packages',
  'peerings',
  'ping',
  'ping_meshes',
  'pipeline_runs',
  'pgsql_databases',
  'pgsql_instances',
  'policies',
  'presentation_instances',
  'principal_assignments',
  'private_endpoint_connection_proxies',
  'private_endpoint_connections',
  'private_endpoints',
  'private_link_resources',
  'private_link_service_proxies',
  'products',
  'projects',
  'publishers',
  'query_text',
  'recommended_sensitivity_labels',
  'recoverable_databases',
  'registered_servers',
  'registrations',
  'regulatory_compliance_assessments',
  'regulatory_compliance_controls',
  'replicas',
  'replications',
  'repository_integrations',
  'reset_sas_kind',
  'reservations',
  'resource_actions',
  'resource_type_registrations',
  'restore_points',
  'return',
  'revisions',
  'roles',
  'rules',
  'run_commands',
  'runs',
  'sandbox_custom_images',
  'schedule_run',
  'scoped_private_link_proxies',
  'scoped_resources',
  'scripts',
  'secure_score_controls',
  'security_alert_policies',
  'server_endpoints',
  'server_instances',
  'service_certificates',
  'service_configs',
  'services',
  'session_clusters',
  'session_hosts',
  'shared_identities',
  'share_subscriptions',
  'shares',
  'snapshots',
  'split',
  'start_menu_items',
  'steps',
  'storage_insight_configs',
  'storage_targets',
  'streaming_locators',
  'streaming_policies',
  'subscriptions',
  'summary_logs',
  'swap',
  'sync_groups',
  'sync_members',
  'tables',
  'tag_rules',
  'target_groups',
  'throughput_pool_accounts',
  'tokens',
  'topics',
  'top_queries',
  'tracks',
  'transforms',
  'try_planned_before_forced_failover',
  'tunnel_policies',
  'unsuspend',
  'update_policies',
  'update_runs',
  'update_strategies',
  'update_summaries',
  'user_provided_function_apps',
  'user_sessions',
  'validate',
  'versions',
  'virtual_machines',
  'virtual_network_peerings',
  'virtual_network_rules',
  'vulnerability_assessments',
  'vm_applications',
  'wcf_relays',
  'webhooks',
  'worker_pools',
  'workload_groups',
]);

/** Component 4: CAF region example set (reference only; not enforced by allowlist). */
export const COMPONENT4_REGION = new Set([
  'east_us',
  'east_us_2',
  'west_us',
  'west_us_2',
  'west_us_3',
  'central_us',
  'south_central_us',
  'north_central_us',
  'west_europe',
  'north_europe',
  'uk_south',
  'france_central',
  'germany_west_central',
  'canada_central',
  'brazil_south',
  'australia_east',
  'southeast_asia',
  'east_asia',
  'japan_east',
  'korea_central',
]);
