//
// CAF Component 1–4 allowlist data for Azure resource naming (CAF). See
// MANUAL.md § CAF allowlist specification. Used for CAF-style resource
// and document naming only, not for directory path validation.
// Segment values (e.g. resource_group) are CAF name segments; in docs use
// ARM prose terms (e.g. resource group, resource type).
//

/** Component 1: CAF workload/application names only. */
export const COMPONENT1_WORKLOAD = new Set([
  'analytics',
  'application',
  'api',
  'auth',
  'backend',
  'billing',
  'client',
  'dashboard',
  'emissions',
  'gateway',
  'hadoop',
  'identity',
  'ingest',
  'navigator',
  'orders',
  'pipeline',
  'portal',
  'reporting',
  'scheduler',
  'sharepoint',
  'shared',
  'sso',
  'storefront',
  'sync',
  'web',
  'warehouse',
  'worker',
]);

/** Component 2: CAF resource type — major (as-is) + non-major full form. */
export const COMPONENT2_RESOURCE_TYPE = new Set([
  'app',
  'redis',
  'sql',
  'test',
  'prod',
  'dev',
  'qa',
  'stage',
  'config',
  'log',
  'resource_group',
  'storage',
  'virtual_machine',
  'virtual_network',
  'function',
  'sql_database',
  'key_vault',
  'network_interface',
  'network_security_group',
  'public_ip',
  'virtual_network_gateway',
  'subnet',
  'cosmos_db',
  'data_factory',
  'event_hub',
  'service_bus_namespace',
  'service_bus_queue',
  'service_bus_topic',
  'api_management',
  'container_registry',
  'kubernetes_service',
  'mysql_database',
  'postgresql',
  'sql_managed_instance',
  'datalake_store',
  'synapse_workspace',
  'machine_learning_workspace',
  'openai',
  'application_insights',
  'app_service_environment',
  'app_service_plan',
  'virtual_machine_scale_set',
  'private_link',
  'private_endpoint',
  'azure_firewall',
  'application_gateway',
  'recovery_services_vault',
  'management_group',
  'template_spec',
  'automation_account',
  'logic_app',
  'integration_account',
  'bot_service',
  'search',
  'maps',
  'signalr',
  'web_pub_sub',
]);

/** Component 2: Abbreviation → full form (CAF normalization). */
export const COMPONENT2_ABBREV_TO_FULL: Readonly<Record<string, string>> = {
  rg: 'resource_group',
  st: 'storage',
  vm: 'virtual_machine',
  vnet: 'virtual_network',
  func: 'function',
  sqldb: 'sql_database',
  kv: 'key_vault',
  nic: 'network_interface',
  nsg: 'network_security_group',
  pip: 'public_ip',
  vgw: 'virtual_network_gateway',
  snet: 'subnet',
  cosmos: 'cosmos_db',
  adf: 'data_factory',
  evh: 'event_hub',
  sbns: 'service_bus_namespace',
  sbq: 'service_bus_queue',
  sbt: 'service_bus_topic',
  apim: 'api_management',
  cr: 'container_registry',
  aks: 'kubernetes_service',
  mysql: 'mysql_database',
  psql: 'postgresql',
  sqlmi: 'sql_managed_instance',
  dls: 'datalake_store',
  synw: 'synapse_workspace',
  mlw: 'machine_learning_workspace',
  oai: 'openai',
  appi: 'application_insights',
  ase: 'app_service_environment',
  asp: 'app_service_plan',
  vmss: 'virtual_machine_scale_set',
  pl: 'private_link',
  pep: 'private_endpoint',
  afw: 'azure_firewall',
  agw: 'application_gateway',
  rsv: 'recovery_services_vault',
  mg: 'management_group',
  ts: 'template_spec',
  aa: 'automation_account',
  logic: 'logic_app',
  ia: 'integration_account',
  bot: 'bot_service',
  srch: 'search',
  map: 'maps',
  sigr: 'signalr',
  wps: 'web_pub_sub',
} as const;

/** Component 3: CAF environment only. */
export const COMPONENT3_ENVIRONMENT = new Set([
  'prod',
  'dev',
  'test',
  'qa',
  'stage',
]);

/** Component 4: CAF region example set only. */
export const COMPONENT4_REGION = new Set([
  'east_us',
  'east_us_2',
  'west_us',
  'west_us_2',
  'west_us_3',
  'central_us',
  'south_central_us',
  'north_central_us',
  'west_europe',
  'north_europe',
  'uk_south',
  'france_central',
  'germany_west_central',
  'canada_central',
  'brazil_south',
  'australia_east',
  'southeast_asia',
  'east_asia',
  'japan_east',
  'korea_central',
]);
