/**
 * Layer allowed infix sets per store.md §E.
 */

export const LAYER_INFIX: Record<string, Set<string>> = {
  presentation: new Set([
    'router',
    'facade',
    'interceptor',
    'filter',
    'guard',
    'client',
    'validator',
    'payload',
    'session',
    'document',
  ]),
  application: new Set([
    'service',
    'facade',
    'agent',
    'worker',
    'guard',
    'validator',
    'payload',
    'session',
    'document',
    'record',
    'read',
    'write',
    'batch',
    'parse',
    'search',
    'validate',
    'migration',
    'recovery',
  ]),
  domain: new Set([
    'entity',
    'repository',
    'service',
    'record',
    'document',
    'validate',
  ]),
  infrastructure: new Set([
    'adapter',
    'client',
    'repository',
    'agent',
    'worker',
    'blob',
    'cache',
    'session',
    'record',
    'json',
    'sql',
    'redis',
    'stream',
    'document',
    'bootstrap',
    'shutdown',
    'read',
    'write',
    'batch',
    'migration',
    'recovery',
    'parse',
    'upload',
  ]),
};
